import { format, isValid } from "date-fns";
import { parse as chronoParse } from "chrono-node";

const timezoneMap: Record<string, string> = {
  // North America
  EST: "America/New_York",
  EDT: "America/New_York",
  CST: "America/Chicago",
  CDT: "America/Chicago",
  MST: "America/Denver",
  MDT: "America/Denver",
  PST: "America/Los_Angeles",
  PDT: "America/Los_Angeles",
  AKST: "America/Anchorage",
  AKDT: "America/Anchorage",
  HST: "Pacific/Honolulu",
  ET: "America/New_York",
  PT: "America/Los_Angeles",
  MT: "America/Denver",
  CT: "America/Chicago",

  // Europe — fixed offsets so the abbreviation always means its stated UTC offset
  GMT: "UTC",
  UTC: "UTC",
  CET: "Etc/GMT-1",
  CEST: "Etc/GMT-2",
  EET: "Etc/GMT-2",
  EEST: "Etc/GMT-3",
  WET: "UTC",
  WEST: "Etc/GMT-1",
  BST: "Etc/GMT-1",

  // South America
  BRT: "America/Sao_Paulo",
  BRST: "America/Sao_Paulo",
  BRL: "America/Sao_Paulo",

  // Asia/Pacific
  JST: "Asia/Tokyo",
  KST: "Asia/Seoul",
  IST: "Asia/Kolkata",
  SGT: "Asia/Singapore",
  HKT: "Asia/Hong_Kong",
  WIB: "Asia/Jakarta",
  MSK: "Europe/Moscow",
  AEST: "Australia/Sydney",
  AEDT: "Australia/Sydney",
  ACST: "Australia/Adelaide",
  ACDT: "Australia/Adelaide",
  AWST: "Australia/Perth",
  NZST: "Pacific/Auckland",
  NZDT: "Pacific/Auckland",
};

const cityMap: Record<string, string> = {
  // Americas — USA
  "new york": "America/New_York",
  "nova york": "America/New_York",
  boston: "America/New_York",
  philadelphia: "America/New_York",
  miami: "America/New_York",
  atlanta: "America/New_York",
  detroit: "America/Detroit",
  indianapolis: "America/Indiana/Indianapolis",
  nashville: "America/Chicago",
  "new orleans": "America/Chicago",
  chicago: "America/Chicago",
  milwaukee: "America/Chicago",
  minneapolis: "America/Chicago",
  "kansas city": "America/Chicago",
  dallas: "America/Chicago",
  houston: "America/Chicago",
  "san antonio": "America/Chicago",
  denver: "America/Denver",
  phoenix: "America/Phoenix",
  "las vegas": "America/Los_Angeles",
  "los angeles": "America/Los_Angeles",
  "san francisco": "America/Los_Angeles",
  "são francisco": "America/Los_Angeles",
  seattle: "America/Los_Angeles",
  portland: "America/Los_Angeles",
  // Americas — Canada
  toronto: "America/Toronto",
  ottawa: "America/Toronto",
  montreal: "America/Toronto",
  québec: "America/Toronto",
  quebec: "America/Toronto",
  calgary: "America/Edmonton",
  edmonton: "America/Edmonton",
  vancouver: "America/Vancouver",
  // Americas — Latin America
  "mexico city": "America/Mexico_City",
  "ciudad de mexico": "America/Mexico_City",
  guadalajara: "America/Mexico_City",
  monterrey: "America/Monterrey",
  havana: "America/Havana",
  havana: "America/Havana",
  "san jose": "America/Costa_Rica",
  "san josé": "America/Costa_Rica",
  panama: "America/Panama",
  "panama city": "America/Panama",
  bogota: "America/Bogota",
  bogotá: "America/Bogota",
  "rio de janeiro": "America/Sao_Paulo",
  rio: "America/Sao_Paulo",
  "sao paulo": "America/Sao_Paulo",
  "são paulo": "America/Sao_Paulo",
  brasilia: "America/Sao_Paulo",
  brasília: "America/Sao_Paulo",
  fortaleza: "America/Fortaleza",
  recife: "America/Recife",
  manaus: "America/Manaus",
  "belo horizonte": "America/Sao_Paulo",
  salvador: "America/Bahia",
  "porto alegre": "America/Sao_Paulo",
  lima: "America/Lima",
  quito: "America/Guayaquil",
  caracas: "America/Caracas",
  "buenos aires": "America/Argentina/Buenos_Aires",
  santiago: "America/Santiago",
  montevideo: "America/Montevideo",
  asuncion: "America/Asuncion",
  assunção: "America/Asuncion",
  "la paz": "America/La_Paz",
  // Europe — UK & Ireland
  london: "Europe/London",
  londres: "Europe/London",
  manchester: "Europe/London",
  manchester: "Europe/London",
  birmingham: "Europe/London",
  edinburgh: "Europe/London",
  edimburgo: "Europe/London",
  glasgow: "Europe/London",
  liverpool: "Europe/London",
  leeds: "Europe/London",
  sheffield: "Europe/London",
  bristol: "Europe/London",
  newcastle: "Europe/London",
  cardiff: "Europe/London",
  cardife: "Europe/London",
  belfast: "Europe/London",
  belfast: "Europe/London",
  dublin: "Europe/Dublin",
  dublim: "Europe/Dublin",
  // Europe — Western & Central
  paris: "Europe/Paris",
  lyon: "Europe/Paris",
  marseille: "Europe/Paris",
  nice: "Europe/Paris",
  toulouse: "Europe/Paris",
  bordeaux: "Europe/Paris",
  strasbourg: "Europe/Paris",
  berlin: "Europe/Berlin",
  hamburg: "Europe/Berlin",
  munich: "Europe/Berlin",
  munique: "Europe/Berlin",
  münchen: "Europe/Berlin",
  frankfurt: "Europe/Berlin",
  cologne: "Europe/Berlin",
  colônia: "Europe/Berlin",
  köln: "Europe/Berlin",
  dusseldorf: "Europe/Berlin",
  düsseldorf: "Europe/Berlin",
  stuttgart: "Europe/Berlin",
  madrid: "Europe/Madrid",
  barcelona: "Europe/Madrid",
  seville: "Europe/Madrid",
  sevilla: "Europe/Madrid",
  sevilha: "Europe/Madrid",
  valencia: "Europe/Madrid",
  rome: "Europe/Rome",
  roma: "Europe/Rome",
  milan: "Europe/Rome",
  milão: "Europe/Rome",
  milano: "Europe/Rome",
  naples: "Europe/Rome",
  nápoles: "Europe/Rome",
  napoli: "Europe/Rome",
  florence: "Europe/Rome",
  florença: "Europe/Rome",
  firenze: "Europe/Rome",
  venice: "Europe/Rome",
  veneza: "Europe/Rome",
  venezia: "Europe/Rome",
  turin: "Europe/Rome",
  torino: "Europe/Rome",
  amsterdam: "Europe/Amsterdam",
  rotterdam: "Europe/Amsterdam",
  "the hague": "Europe/Amsterdam",
  "den haag": "Europe/Amsterdam",
  brussels: "Europe/Brussels",
  bruxelas: "Europe/Brussels",
  bruxelles: "Europe/Brussels",
  antwerp: "Europe/Brussels",
  antuérpia: "Europe/Brussels",
  antwerpen: "Europe/Brussels",
  ghent: "Europe/Brussels",
  gante: "Europe/Brussels",
  vienna: "Europe/Vienna",
  viena: "Europe/Vienna",
  wien: "Europe/Vienna",
  zurich: "Europe/Zurich",
  zurique: "Europe/Zurich",
  zürich: "Europe/Zurich",
  geneva: "Europe/Zurich",
  genebra: "Europe/Zurich",
  genève: "Europe/Zurich",
  bern: "Europe/Zurich",
  berna: "Europe/Zurich",
  luxembourg: "Europe/Luxembourg",
  luxemburgo: "Europe/Luxembourg",
  lisbon: "Europe/Lisbon",
  lisboa: "Europe/Lisbon",
  porto: "Europe/Lisbon",
  // Europe — Northern
  stockholm: "Europe/Stockholm",
  estocolmo: "Europe/Stockholm",
  oslo: "Europe/Oslo",
  helsinki: "Europe/Helsinki",
  helsinque: "Europe/Helsinki",
  copenhagen: "Europe/Copenhagen",
  copenhague: "Europe/Copenhagen",
  københavn: "Europe/Copenhagen",
  reykjavik: "Atlantic/Reykjavik",
  reiquiavique: "Atlantic/Reykjavik",
  // Europe — Eastern & Balkans
  moscow: "Europe/Moscow",
  moscou: "Europe/Moscow",
  moskva: "Europe/Moscow",
  "saint petersburg": "Europe/Moscow",
  "são petersburgo": "Europe/Moscow",
  kyiv: "Europe/Kiev",
  kiev: "Europe/Kiev",
  minsk: "Europe/Minsk",
  warsaw: "Europe/Warsaw",
  varsóvia: "Europe/Warsaw",
  warszawa: "Europe/Warsaw",
  prague: "Europe/Prague",
  praga: "Europe/Prague",
  praha: "Europe/Prague",
  budapest: "Europe/Budapest",
  bratislava: "Europe/Bratislava",
  zagreb: "Europe/Zagreb",
  belgrade: "Europe/Belgrade",
  belgrado: "Europe/Belgrade",
  sarajevo: "Europe/Sarajevo",
  ljubljana: "Europe/Ljubljana",
  skopje: "Europe/Skopje",
  tirana: "Europe/Tirane",
  tirана: "Europe/Tirane",
  podgorica: "Europe/Podgorica",
  sofia: "Europe/Sofia",
  bucharest: "Europe/Bucharest",
  bucareste: "Europe/Bucharest",
  athens: "Europe/Athens",
  atenas: "Europe/Athens",
  thessaloniki: "Europe/Athens",
  vilnius: "Europe/Vilnius",
  riga: "Europe/Riga",
  tallinn: "Europe/Tallinn",
  istanbul: "Europe/Istanbul",
  istambul: "Europe/Istanbul",
  ankara: "Europe/Istanbul",
  // Asia — East
  tokyo: "Asia/Tokyo",
  tóquio: "Asia/Tokyo",
  osaka: "Asia/Tokyo",
  nagoya: "Asia/Tokyo",
  kyoto: "Asia/Tokyo",
  sapporo: "Asia/Tokyo",
  fukuoka: "Asia/Tokyo",
  seoul: "Asia/Seoul",
  seul: "Asia/Seoul",
  busan: "Asia/Seoul",
  incheon: "Asia/Seoul",
  beijing: "Asia/Shanghai",
  pequim: "Asia/Shanghai",
  peking: "Asia/Shanghai",
  shanghai: "Asia/Shanghai",
  shenzhen: "Asia/Shanghai",
  guangzhou: "Asia/Shanghai",
  chengdu: "Asia/Shanghai",
  wuhan: "Asia/Shanghai",
  hangzhou: "Asia/Shanghai",
  chongqing: "Asia/Shanghai",
  tianjin: "Asia/Shanghai",
  nanjing: "Asia/Shanghai",
  "hong kong": "Asia/Hong_Kong",
  taipei: "Asia/Taipei",
  taipé: "Asia/Taipei",
  // Asia — Southeast
  singapore: "Asia/Singapore",
  singapura: "Asia/Singapore",
  bangkok: "Asia/Bangkok",
  bancoque: "Asia/Bangkok",
  hanoi: "Asia/Bangkok",
  "ho chi minh": "Asia/Ho_Chi_Minh",
  "ho chi minh city": "Asia/Ho_Chi_Minh",
  "cidade de ho chi minh": "Asia/Ho_Chi_Minh",
  jakarta: "Asia/Jakarta",
  jacarta: "Asia/Jakarta",
  manila: "Asia/Manila",
  manilha: "Asia/Manila",
  "kuala lumpur": "Asia/Kuala_Lumpur",
  "phnom penh": "Asia/Phnom_Penh",
  "nom pen": "Asia/Phnom_Penh",
  yangon: "Asia/Rangoon",
  rangoon: "Asia/Rangoon",
  vientiane: "Asia/Vientiane",
  // Asia — South
  mumbai: "Asia/Kolkata",
  bombaim: "Asia/Kolkata",
  bombay: "Asia/Kolkata",
  delhi: "Asia/Kolkata",
  "new delhi": "Asia/Kolkata",
  "nova delhi": "Asia/Kolkata",
  kolkata: "Asia/Kolkata",
  calcutá: "Asia/Kolkata",
  bangalore: "Asia/Kolkata",
  hyderabad: "Asia/Kolkata",
  chennai: "Asia/Kolkata",
  pune: "Asia/Kolkata",
  karachi: "Asia/Karachi",
  islamabad: "Asia/Karachi",
  lahore: "Asia/Karachi",
  dhaka: "Asia/Dhaka",
  daca: "Asia/Dhaka",
  colombo: "Asia/Colombo",
  kathmandu: "Asia/Kathmandu",
  katmandu: "Asia/Kathmandu",
  // Asia — Middle East & Central
  dubai: "Asia/Dubai",
  "abu dhabi": "Asia/Dubai",
  "abu dabi": "Asia/Dubai",
  muscat: "Asia/Muscat",
  mascate: "Asia/Muscat",
  doha: "Asia/Qatar",
  "kuwait city": "Asia/Kuwait",
  kuwait: "Asia/Kuwait",
  riyadh: "Asia/Riyadh",
  riade: "Asia/Riyadh",
  amman: "Asia/Amman",
  amã: "Asia/Amman",
  beirut: "Asia/Beirut",
  beirute: "Asia/Beirut",
  damascus: "Asia/Damascus",
  damasco: "Asia/Damascus",
  "tel aviv": "Asia/Jerusalem",
  "tel aviv-yafo": "Asia/Jerusalem",
  tehran: "Asia/Tehran",
  teerã: "Asia/Tehran",
  baghdad: "Asia/Baghdad",
  bagdá: "Asia/Baghdad",
  tashkent: "Asia/Tashkent",
  tachkente: "Asia/Tashkent",
  almaty: "Asia/Almaty",
  baku: "Asia/Baku",
  tbilisi: "Asia/Tbilisi",
  yerevan: "Asia/Yerevan",
  // Africa
  cairo: "Africa/Cairo",
  "el cairo": "Africa/Cairo",
  alexandria: "Africa/Cairo",
  tripoli: "Africa/Tripoli",
  trípoli: "Africa/Tripoli",
  tunis: "Africa/Tunis",
  algiers: "Africa/Algiers",
  argel: "Africa/Algiers",
  casablanca: "Africa/Casablanca",
  dakar: "Africa/Dakar",
  accra: "Africa/Accra",
  abidjan: "Africa/Abidjan",
  lagos: "Africa/Lagos",
  nairobi: "Africa/Nairobi",
  "dar es salaam": "Africa/Dar_es_Salaam",
  "dar es salã": "Africa/Dar_es_Salaam",
  kampala: "Africa/Kampala",
  khartoum: "Africa/Khartoum",
  cartum: "Africa/Khartoum",
  "addis ababa": "Africa/Addis_Ababa",
  "adis abeba": "Africa/Addis_Ababa",
  johannesburg: "Africa/Johannesburg",
  joanesburgo: "Africa/Johannesburg",
  capetown: "Africa/Johannesburg",
  "cape town": "Africa/Johannesburg",
  "cidade do cabo": "Africa/Johannesburg",
  kinshasa: "Africa/Kinshasa",
  luanda: "Africa/Luanda",
  lusaka: "Africa/Lusaka",
  harare: "Africa/Harare",
  maputo: "Africa/Maputo",
  // Oceania
  sydney: "Australia/Sydney",
  sidney: "Australia/Sydney",
  "gold coast": "Australia/Brisbane",
  brisbane: "Australia/Brisbane",
  melbourne: "Australia/Melbourne",
  canberra: "Australia/Sydney",
  hobart: "Australia/Hobart",
  adelaide: "Australia/Adelaide",
  darwin: "Australia/Darwin",
  perth: "Australia/Perth",
  auckland: "Pacific/Auckland",
  "nova zelândia": "Pacific/Auckland",
  wellington: "Pacific/Auckland",
  christchurch: "Pacific/Auckland",
  honolulu: "Pacific/Honolulu",
};

const resolveLocation = (location: string): string | null => {
  const upper = location.toUpperCase();
  if (timezoneMap[upper]) return timezoneMap[upper];
  const lower = location.toLowerCase();
  if (cityMap[lower]) return cityMap[lower];
  return location;
};

export const Dates = {
  valid: isValid,
  isoDate: (d: Date) => format(d, "yyyy-MM-dd"),
  time: (d: Date) => format(d, "HH:mm"),
  yearMonthDay: (d: Date) => format(d, "yyyy-MM-dd"),
  evaluateTimezone: (expr: string): string | null => {
    const match = expr.match(/^(.+?)\s+(?:in|to)\s+(.+)$/i);
    if (!match) return null;
    const timePart = match[1]!.trim();
    const locationRaw = match[2]!.trim();
    const targetIANA = resolveLocation(locationRaw);
    if (!targetIANA) return null;
    try {
      const date = /^now$/i.test(timePart)
        ? new Date()
        : (() => {
            const results = chronoParse(timePart);
            if (results.length === 0) return null;
            const result = results[0]!;
            if ((result.start as any).knownValues.hour === undefined)
              return null;
            return result.start.date();
          })();
      if (!date) return null;
      return new Intl.DateTimeFormat(undefined, {
        timeZone: targetIANA,
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
        timeZoneName: "short",
      }).format(date);
    } catch {
      return null;
    }
  },
};
